apiVersion: apps/v1
kind: Deployment
metadata:
  name: intranet-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: intranet-postgres
  template:
    metadata:
      labels:
        app: intranet-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:17
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: intranet-secrets
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: intranet-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: intranet-secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: intranet-postgres-service
spec:
  selector:
    app: intranet-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432